stages:
  preprocess_raw:
    cmd: python scripts/raw_preprocess.py --cfg configs/dataloader_raw.yaml
    deps:
      - scripts/raw_preprocess.py
      - configs/dataloader_raw.yaml
      - filters   # RAW source hierarchy
    outs:
      - pipeline/raw_master
      - pipeline/space2depth
  augment_train:
    cmd: python scripts/gen_aug_train.py pipeline/raw_master pipeline/aug_train --config configs/augmentations.yaml -j 0
    deps:
      - scripts/gen_aug_train.py
      - pipeline/raw_master
    outs:
      - pipeline/aug_train
